### PR TITLE
Issue 366

### PR DESCRIPTION
**Pull request by tfausak**

### CODE REVIEW

**Comment by ulysses4ever** [comment]
@tfausak thank you for the context! I'm down to anything but let me check that i understand it right. Currently, i can't push to master from my local checkout but i am able to create a pull request against the master branch and merge it myself? If this is the case, then (a) i think it's a very fine way to set things up, (b) i don't see a need to change anything on your side. In particular, i assumed that i should create a PR every time anyway. 

But if you really want to switch things, I'm fine with that too. I just hope that me being listed as a contributor **doesn't bring you more work**.  I really appreciate your time and grateful for all the work you're doing here.

**Comment by tfausak** [comment]
I'm not sure if you have the ability to merge your own pull requests or not. I think you do, but it's hard for me to check 😄 

Creating the newsletter issues through pull requests isn't really any more difficult for me. It should make things easier for you, since you can simply push to the current issue's branch rather than making a new PR each time. Also it should make it easier for drive-by contributors to find the right issue to contribute to.

**Comment by ulysses4ever** [comment]
All right then: sounds like a good way to go. Thanks!

**Comment by alexeyzab** [comment]
Nice, thank you @tfausak!

**Pull request merged**
