### PR TITLE
Introducing `runhs`

### PR DESCRIPTION
**Pull request by friedbrice**
Okay, this is pure cheese, but whatever.

### CODE REVIEW

**Comment by tfausak** [comment]
Looks cool! Unfortunately, as much as I like it, that description is a little long. Can you edit it down?

**Comment by friedbrice** [comment]
yep :-) on it

**Comment by friedbrice** [comment]
Sorry, didn't mean to hold up release! I will close this and open a new PR on next week's newsletter.

**Comment by tfausak** [comment]
No problem! I'll get the upcoming issue stubbed out soon.

**Comment by tfausak** [comment]
I included a brief mention of `runhs` in the upcoming issue. Let me know if you'd like to change or remove it. 

https://github.com/haskellweekly/haskellweekly/blob/214bcbab98a5ad85c8870a3c5e7ceeca55a24393/data/newsletter/issue-223.markdown#show--tell

**Comment by friedbrice** [comment]
Hi Taylor,

That is great! And that is exactly the niche I hope this fills: casual programmers who just want to focus on the code.

TYVM :-)

**Comment by friedbrice** [comment]
Hmm, for some reason, when I merge in your repo's HEAD, I get something different from what I see on Github (otherwise I'd make a pull request), but in lieu of a pull request, can I suggest this revised copy, below?

> Skip the minutia of project management, cabal files, or hpack. Get your casual-programming friends setup to use Haskell, with all the greatest libraries, for their one-off scripting and data munging tasks.

Thanks!
Daniel

**Comment by tfausak** [comment]
Weird! 

I committed that in ab4b4aefec907d3b3a44c1dcf09406054a363e24.

**Comment by friedbrice** [comment]
thanks very much :-D

**Pull request closed without merging**
